# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  readme-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cowsay and fortune
        run: sudo apt-get install cowsay fortune
      - name: Install Rich
        run: pip3 install rich
      - name: Setup Git
        run: git config --global user.name "cakiki" && git config --global user.email "cakiki@protonmail.com"
      - name: Generate README.md and commit
        run: |
          cd $GITHUB_WORKSPACE 
          ./readme.py
          git add README.md || echo "No changes to file"
          git commit -m "Generate new README file" || echo "Nothing to commit"
          git push origin || echo "Nothing to commit"
