# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cowsay
        run: sudo apt-get install cowsay
      - name: Install Rich
        run: pip3 install rich
      - name: Generate README.md and commit
        run: ./readmy.py && git add README.md && git commit -m "Generate new README file" && git push origin
